CREATE TABLE connector_realtime_events (
    sequence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(36) NOT NULL UNIQUE,
    tenant_id VARCHAR(80) NOT NULL,
    event_type VARCHAR(140) NOT NULL,
    aggregate_id VARCHAR(180) NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    payload TEXT NOT NULL
);

CREATE INDEX idx_connector_realtime_tenant_sequence
    ON connector_realtime_events(tenant_id, sequence_id);

CREATE INDEX idx_connector_realtime_occurred
    ON connector_realtime_events(occurred_at);
