CREATE TABLE service_metadata (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name    VARCHAR(80)  NOT NULL UNIQUE,
    schema_version  VARCHAR(32)  NOT NULL,
    initialized_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO service_metadata (service_name, schema_version)
VALUES ('ai-agent-service', '1.0.0');
